global:
  image: test
  replicas: 1
  bootstrapServers: kafka-cp-kafka-headless:9092
  resources:
    requests:
      cpu: "0.25"
      memory: 256Mi
    limits:
      cpu: "0.5"
      memory: 1Gi
  readinessProbe:
    initialDelaySeconds: 15
    timeoutSeconds: 5
  livenessProbe:
    initialDelaySeconds: 15
    timeoutSeconds: 5